////////////////////////////////////////////////////////////////////////
//
// MPDSchemaTest.h
//
// This file was generated by XMLSpy 2012r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef MPDSchemaTest_H_INCLUDED
#define MPDSchemaTest_H_INCLUDED


#include "Resource.h"


#endif // MPDSchemaTest_H_INCLUDED
