#ifndef AAA_COMMON_CUSTOM_H_
#define AAA_COMMON_CUSTOM_H_


MBOOL CUST_ENABLE_PRECAPTURE_AF(void);
MBOOL CUST_PRECAPTURE_AF_AFTER_PREFLASH(void);
MBOOL CUST_ENABLE_VIDEO_AUTO_FLASH(void);
MBOOL CUST_CAF_WINDOW_FOLLOW_TAF_WINDOW(void);
MBOOL CUST_ONE_SHOT_AE_BEFORE_TAF(void);
MBOOL CUST_SKIP_ONE_SHOT_AE_FOR_TAF(void);
MBOOL CUST_ENABLE_TOUCH_AE(void);
MBOOL CUST_ENABLE_FACE_AE(void);
MBOOL CUST_LOCK_AE_DURING_CAF(void);
MBOOL CUST_ENABLE_VIDEO_DYNAMIC_FRAME_RATE(void);


#endif /* AAA_COMMON_CUSTOM_H_ */

