 #ifndef _DBG_N3D_AWB_PARAM_H_
#define _DBG_N3D_AWB_PARAM_H_




enum
{
	//Intermedium Data
    N3D_AWB_TAG_DEBUG_VERSION = N3D_AE_TAG_MAX,
    N3D_AWB_MODE,
    N3D_AWB_WHITE_DETECTION_MODE,
    N3D_AWB_AUTO_CHANNEL,

    //Input Data - Main
    N3D_AWB_MAIN_NORMAL_WB_HORIZON_GAIN_R,
    N3D_AWB_MAIN_NORMAL_WB_HORIZON_GAIN_G,
    N3D_AWB_MAIN_NORMAL_WB_HORIZON_GAIN_B,
    N3D_AWB_MAIN_HORIZON_CCT,
    N3D_AWB_MAIN_NORMAL_WB_A_GAIN_R,
    N3D_AWB_MAIN_NORMAL_WB_A_GAIN_G,
    N3D_AWB_MAIN_NORMAL_WB_A_GAIN_B,
    N3D_AWB_MAIN_A_CCT,
    N3D_AWB_MAIN_NORMAL_WB_TL84_GAIN_R,
    N3D_AWB_MAIN_NORMAL_WB_TL84_GAIN_G,
    N3D_AWB_MAIN_NORMAL_WB_TL84_GAIN_B,
    N3D_AWB_MAIN_NORMAL_WB_CWF_GAIN_R,
    N3D_AWB_MAIN_NORMAL_WB_CWF_GAIN_G,
    N3D_AWB_MAIN_NORMAL_WB_CWF_GAIN_B,
    N3D_AWB_MAIN_TL84_CCT,
    N3D_AWB_MAIN_NORMAL_WB_DNP_GAIN_R,
    N3D_AWB_MAIN_NORMAL_WB_DNP_GAIN_G,
    N3D_AWB_MAIN_NORMAL_WB_DNP_GAIN_B,
    N3D_AWB_MAIN_DNP_CCT,
    N3D_AWB_MAIN_NORMAL_WB_D65_GAIN_R,
    N3D_AWB_MAIN_NORMAL_WB_D65_GAIN_G,
    N3D_AWB_MAIN_NORMAL_WB_D65_GAIN_B,
    N3D_AWB_MAIN_D65_CCT,
    N3D_AWB_MAIN_UNIT_GAIN_R,
    N3D_AWB_MAIN_UNIT_GAIN_G,
    N3D_AWB_MAIN_UNIT_GAIN_B,
    N3D_AWB_MAIN_GOLDEN_GAIN_R,
    N3D_AWB_MAIN_GOLDEN_GAIN_G,
    N3D_AWB_MAIN_GOLDEN_GAIN_B,
    N3D_AWB_MAIN_CURR_GAIN_R,
    N3D_AWB_MAIN_CURR_GAIN_G,
    N3D_AWB_MAIN_CURR_GAIN_B,
    N3D_AWB_MAIN_CURR_ALG_GAIN_R,
    N3D_AWB_MAIN_CURR_ALG_GAIN_G,
    N3D_AWB_MAIN_CURR_ALG_GAIN_B,
    N3D_AWB_MAIN_CURR_TARGET_GAIN_R,
    N3D_AWB_MAIN_CURR_TARGET_GAIN_G,
    N3D_AWB_MAIN_CURR_TARGET_GAIN_B,
    N3D_AWB_MAIN_CURR_CCT,
    N3D_AWB_MAIN_CURR_LIGHT_MODE,
    N3D_AWB_MAIN_CURR_LV,
    N3D_AWB_MAIN_CURR_TUNGSTEN_P,
    N3D_AWB_MAIN_CURR_WARM_FLUORESCENT_P,
    N3D_AWB_MAIN_CURR_FLUORESCENT_P,
    N3D_AWB_MAIN_CURR_CWF_P,
    N3D_AWB_MAIN_CURR_DAYLIGHT_P,
    N3D_AWB_MAIN_CURR_SHADE_P,
    N3D_AWB_MAIN_CURR_DAYLIGHT_FLUORESCENT_P,

	//Input Data - Sub
    N3D_AWB_SUB_NORMAL_WB_HORIZON_GAIN_R,
    N3D_AWB_SUB_NORMAL_WB_HORIZON_GAIN_G,
    N3D_AWB_SUB_NORMAL_WB_HORIZON_GAIN_B,
    N3D_AWB_SUB_HORIZON_CCT,
    N3D_AWB_SUB_NORMAL_WB_A_GAIN_R,
    N3D_AWB_SUB_NORMAL_WB_A_GAIN_G,
    N3D_AWB_SUB_NORMAL_WB_A_GAIN_B,
    N3D_AWB_SUB_A_CCT,
    N3D_AWB_SUB_NORMAL_WB_TL84_GAIN_R,
    N3D_AWB_SUB_NORMAL_WB_TL84_GAIN_G,
    N3D_AWB_SUB_NORMAL_WB_TL84_GAIN_B,
    N3D_AWB_SUB_NORMAL_WB_CWF_GAIN_R,
    N3D_AWB_SUB_NORMAL_WB_CWF_GAIN_G,
    N3D_AWB_SUB_NORMAL_WB_CWF_GAIN_B,
    N3D_AWB_SUB_TL84_CCT,
    N3D_AWB_SUB_NORMAL_WB_DNP_GAIN_R,
    N3D_AWB_SUB_NORMAL_WB_DNP_GAIN_G,
    N3D_AWB_SUB_NORMAL_WB_DNP_GAIN_B,
    N3D_AWB_SUB_DNP_CCT,
    N3D_AWB_SUB_NORMAL_WB_D65_GAIN_R,
    N3D_AWB_SUB_NORMAL_WB_D65_GAIN_G,
    N3D_AWB_SUB_NORMAL_WB_D65_GAIN_B,
    N3D_AWB_SUB_D65_CCT,
    N3D_AWB_SUB_UNIT_GAIN_R,
    N3D_AWB_SUB_UNIT_GAIN_G,
    N3D_AWB_SUB_UNIT_GAIN_B,
    N3D_AWB_SUB_GOLDEN_GAIN_R,
    N3D_AWB_SUB_GOLDEN_GAIN_G,
    N3D_AWB_SUB_GOLDEN_GAIN_B,
    N3D_AWB_SUB_CURR_GAIN_R,
    N3D_AWB_SUB_CURR_GAIN_G,
    N3D_AWB_SUB_CURR_GAIN_B,
    N3D_AWB_SUB_CURR_ALG_GAIN_R,
    N3D_AWB_SUB_CURR_ALG_GAIN_G,
    N3D_AWB_SUB_CURR_ALG_GAIN_B,
    N3D_AWB_SUB_CURR_TARGET_GAIN_R,
    N3D_AWB_SUB_CURR_TARGET_GAIN_G,
    N3D_AWB_SUB_CURR_TARGET_GAIN_B,
    N3D_AWB_SUB_CURR_CCT,
    N3D_AWB_SUB_CURR_LIGHT_MODE,
    N3D_AWB_SUB_CURR_LV,
    N3D_AWB_SUB_CURR_TUNGSTEN_P,
    N3D_AWB_SUB_CURR_WARM_FLUORESCENT_P,
    N3D_AWB_SUB_CURR_FLUORESCENT_P,
    N3D_AWB_SUB_CURR_CWF_P,
    N3D_AWB_SUB_CURR_DAYLIGHT_P,
    N3D_AWB_SUB_CURR_SHADE_P,
    N3D_AWB_SUB_CURR_DAYLIGHT_FLUORESCENT_P,

	//Output Data - Main
	N3D_AWB_MAIN_OUTPUT_GAIN_R,
	N3D_AWB_MAIN_OUTPUT_GAIN_G,
	N3D_AWB_MAIN_OUTPUT_GAIN_B,
	N3D_AWB_MAIN_OUTPUT_CCT,

	//Output Data - Sub
	N3D_AWB_SUB_OUTPUT_GAIN_R,
	N3D_AWB_SUB_OUTPUT_GAIN_G,
	N3D_AWB_SUB_OUTPUT_GAIN_B,
	N3D_AWB_SUB_OUTPUT_CCT,

    N3D_AWB_TAG_MAX
};


//N3D AE debug info
#define N3D_AWB_DEBUG_VERSION (1)
#define N3D_AWB_DEBUG_TAG_SIZE (N3D_AWB_TAG_MAX+10)

typedef struct
{
    DEBUG_CAM_TAG_T  Tag[N3D_AWB_DEBUG_TAG_SIZE];

} N3D_AWB_DEBUG_INFO_T;


#endif // _DBG_AE_PARAM_H_
