////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2012r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#ifndef ALTOVA_PREFIX_H_INCLUDED
#define ALTOVA_PREFIX_H_INCLUDED




#include "MPDSchema_debug.h"
#include "MPDSchema_enum.h"


//{{AFX_INSERT_LOCATION}}

#endif // ALTOVA_STDAFX_H_INCLUDED
