////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2012r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#ifndef ALTOVA_XML_PREFIX_H_INCLUDED
#define ALTOVA_XML_PREFIX_H_INCLUDED





#include "MPDSchema_debug.h"
#include "MPDSchema_enum.h"

#include <xercesc/dom/DOM.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>


#ifdef _DEBUG
	#pragma comment(lib, "xerces-c_3D")
#else
	#pragma comment(lib, "xerces-c_3")
#endif




//{{AFX_INSERT_LOCATION}}

#endif // ALTOVA_STDAFX_H_INCLUDED
