////////////////////////////////////////////////////////////////////////
//
// MPDSchema-typeinfo.cpp
//
// This file was generated by XMLSpy 2012r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#include "mpdschema_prefix.h"
#include "MPDSchema-typeinfo.h"
#include "xs-types.h"

namespace MPDSchema
{

const altova::Binder binder = { namespaces, types, members, facets };

// Array of all namespaces with pointers to types:
const altova::NamespaceInfo namespaces[] = 
{
	{ &binder, _T("http://www.w3.org/2001/XMLSchema"), _T("xs"), _altova_tif_xs, _altova_til_xs },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T(""), _altova_tif, _altova_til },
	{ 0 },
};

// Array of all types with pointers to members:
const altova::TypeInfo types[] = 
{
	{ &binder, _altova_ni_xs, _T("ENTITIES"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CENTITIES, _altova_mil_xs_altova_CENTITIES,  0 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("ENTITY"), _altova_ti_xs_altova_CNCName, _altova_mif_xs_altova_CENTITY, _altova_mil_xs_altova_CENTITY,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("ID"), _altova_ti_xs_altova_CNCName, _altova_mif_xs_altova_CID, _altova_mil_xs_altova_CID,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("IDREF"), _altova_ti_xs_altova_CNCName, _altova_mif_xs_altova_CIDREF, _altova_mil_xs_altova_CIDREF,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("IDREFS"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CIDREFS, _altova_mil_xs_altova_CIDREFS,  3 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("NCName"), _altova_ti_xs_altova_CName, _altova_mif_xs_altova_CNCName, _altova_mil_xs_altova_CNCName,  6 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("NMTOKEN"), _altova_ti_xs_altova_Ctoken, _altova_mif_xs_altova_CNMTOKEN, _altova_mil_xs_altova_CNMTOKEN,  8 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("NMTOKENS"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CNMTOKENS, _altova_mil_xs_altova_CNMTOKENS,  10 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("NOTATION"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CNOTATION, _altova_mil_xs_altova_CNOTATION,  15 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("Name"), _altova_ti_xs_altova_Ctoken, _altova_mif_xs_altova_CName, _altova_mil_xs_altova_CName,  17 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("QName"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CQName, _altova_mil_xs_altova_CQName,  19 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("anySimpleType"), ~0, _altova_mif_xs_altova_CanySimpleType, _altova_mil_xs_altova_CanySimpleType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("anyType"), ~0, _altova_mif_xs_altova_CanyType, _altova_mil_xs_altova_CanyType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("anyURI"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CanyURI, _altova_mil_xs_altova_CanyURI,  21 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("base64Binary"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cbase64Binary, _altova_mil_xs_altova_Cbase64Binary,  23 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("boolean"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cboolean, _altova_mil_xs_altova_Cboolean,  25 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("byte"), _altova_ti_xs_altova_Cshort, _altova_mif_xs_altova_Cbyte, _altova_mil_xs_altova_Cbyte,  27 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("date"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cdate, _altova_mil_xs_altova_Cdate,  30 , altova::Whitespace_Collapse, &altova::DateFormatter },
	{ &binder, _altova_ni_xs, _T("dateTime"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CdateTime, _altova_mil_xs_altova_CdateTime,  32 , altova::Whitespace_Collapse, &altova::DateTimeFormatter },
	{ &binder, _altova_ni_xs, _T("decimal"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cdecimal, _altova_mil_xs_altova_Cdecimal,  34 , altova::Whitespace_Collapse, &altova::DecimalFormatter },
	{ &binder, _altova_ni_xs, _T("double"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cdouble, _altova_mil_xs_altova_Cdouble,  36 , altova::Whitespace_Collapse, &altova::DoubleFormatter },
	{ &binder, _altova_ni_xs, _T("duration"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cduration, _altova_mil_xs_altova_Cduration,  38 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("float"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cfloat, _altova_mil_xs_altova_Cfloat,  40 , altova::Whitespace_Collapse, &altova::DoubleFormatter },
	{ &binder, _altova_ni_xs, _T("gDay"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgDay, _altova_mil_xs_altova_CgDay,  42 , altova::Whitespace_Collapse, &altova::GDayFormatter },
	{ &binder, _altova_ni_xs, _T("gMonth"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgMonth, _altova_mil_xs_altova_CgMonth,  44 , altova::Whitespace_Collapse, &altova::GMonthFormatter },
	{ &binder, _altova_ni_xs, _T("gMonthDay"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgMonthDay, _altova_mil_xs_altova_CgMonthDay,  46 , altova::Whitespace_Collapse, &altova::GMonthDayFormatter },
	{ &binder, _altova_ni_xs, _T("gYear"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgYear, _altova_mil_xs_altova_CgYear,  48 , altova::Whitespace_Collapse, &altova::GYearFormatter },
	{ &binder, _altova_ni_xs, _T("gYearMonth"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_CgYearMonth, _altova_mil_xs_altova_CgYearMonth,  50 , altova::Whitespace_Collapse, &altova::GYearMonthFormatter },
	{ &binder, _altova_ni_xs, _T("hexBinary"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_ChexBinary, _altova_mil_xs_altova_ChexBinary,  52 , altova::Whitespace_Collapse, &altova::HexBinaryFormatter },
	{ &binder, _altova_ni_xs, _T("int"), _altova_ti_xs_altova_Clong, _altova_mif_xs_altova_Cint, _altova_mil_xs_altova_Cint,  54 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("integer"), _altova_ti_xs_altova_Cdecimal, _altova_mif_xs_altova_Cinteger, _altova_mil_xs_altova_Cinteger,  57 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("language"), _altova_ti_xs_altova_Ctoken, _altova_mif_xs_altova_Clanguage, _altova_mil_xs_altova_Clanguage,  60 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("long"), _altova_ti_xs_altova_Cinteger, _altova_mif_xs_altova_Clong, _altova_mil_xs_altova_Clong,  62 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("negativeInteger"), _altova_ti_xs_altova_CnonPositiveInteger, _altova_mif_xs_altova_CnegativeInteger, _altova_mil_xs_altova_CnegativeInteger,  65 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("nonNegativeInteger"), _altova_ti_xs_altova_Cinteger, _altova_mif_xs_altova_CnonNegativeInteger, _altova_mil_xs_altova_CnonNegativeInteger,  67 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("nonPositiveInteger"), _altova_ti_xs_altova_Cinteger, _altova_mif_xs_altova_CnonPositiveInteger, _altova_mil_xs_altova_CnonPositiveInteger,  69 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("normalizedString"), _altova_ti_xs_altova_Cstring, _altova_mif_xs_altova_CnormalizedString, _altova_mil_xs_altova_CnormalizedString,  71 , altova::Whitespace_Replace, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("positiveInteger"), _altova_ti_xs_altova_CnonNegativeInteger, _altova_mif_xs_altova_CpositiveInteger, _altova_mil_xs_altova_CpositiveInteger,  73 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("short"), _altova_ti_xs_altova_Cint, _altova_mif_xs_altova_Cshort, _altova_mil_xs_altova_Cshort,  75 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("string"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Cstring, _altova_mil_xs_altova_Cstring,  78 , altova::Whitespace_Preserve, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("time"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_xs_altova_Ctime, _altova_mil_xs_altova_Ctime,  80 , altova::Whitespace_Collapse, &altova::TimeFormatter },
	{ &binder, _altova_ni_xs, _T("token"), _altova_ti_xs_altova_CnormalizedString, _altova_mif_xs_altova_Ctoken, _altova_mil_xs_altova_Ctoken,  82 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedByte"), _altova_ti_xs_altova_CunsignedShort, _altova_mif_xs_altova_CunsignedByte, _altova_mil_xs_altova_CunsignedByte,  84 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedInt"), _altova_ti_xs_altova_CunsignedLong, _altova_mif_xs_altova_CunsignedInt, _altova_mil_xs_altova_CunsignedInt,  86 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedLong"), _altova_ti_xs_altova_CnonNegativeInteger, _altova_mif_xs_altova_CunsignedLong, _altova_mil_xs_altova_CunsignedLong,  88 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T("unsignedShort"), _altova_ti_xs_altova_CunsignedInt, _altova_mif_xs_altova_CunsignedShort, _altova_mil_xs_altova_CunsignedShort,  90 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni_xs, _T(""), ~0, _altova_mif_xs_altova_CanyURIType, _altova_mil_xs_altova_CanyURIType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni_xs, _T(""), ~0, _altova_mif_xs_altova_CstringType, _altova_mil_xs_altova_CstringType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },

	{ &binder, _altova_ni, _T("AdaptationSetType"), _altova_ti_altova_CRepresentationBaseType, _altova_mif_altova_CAdaptationSetType, _altova_mil_altova_CAdaptationSetType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("BaseURLType"), _altova_ti_xs_altova_CanyURIType, _altova_mif_altova_CBaseURLType, _altova_mil_altova_CBaseURLType,  ~0 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T("ConditionalUintType"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_altova_CConditionalUintType, _altova_mil_altova_CConditionalUintType,  92 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T("ContentComponentType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CContentComponentType, _altova_mil_altova_CContentComponentType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("ContentProtectionType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CContentProtectionType, _altova_mil_altova_CContentProtectionType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("DescriptorType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CDescriptorType, _altova_mil_altova_CDescriptorType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("FormatVersionType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CFormatVersionType, _altova_mil_altova_CFormatVersionType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("MPDtype"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CMPDtype, _altova_mil_altova_CMPDtype,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("MS3Type"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CMS3Type, _altova_mil_altova_CMS3Type,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("MarlinBroadbandType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CMarlinBroadbandType, _altova_mil_altova_CMarlinBroadbandType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("MarlinContentIdsType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CMarlinContentIdsType, _altova_mil_altova_CMarlinContentIdsType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("MetricsType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CMetricsType, _altova_mil_altova_CMetricsType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("MultipleSegmentBaseType"), _altova_ti_altova_CSegmentBaseType, _altova_mif_altova_CMultipleSegmentBaseType, _altova_mil_altova_CMultipleSegmentBaseType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("PeriodType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CPeriodType, _altova_mil_altova_CPeriodType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("PresentationType"), _altova_ti_xs_altova_Cstring, _altova_mif_altova_CPresentationType, _altova_mil_altova_CPresentationType,  95 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T("ProgramInformationType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CProgramInformationType, _altova_mil_altova_CProgramInformationType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("RangeType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CRangeType, _altova_mil_altova_CRangeType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("RepresentationBaseType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CRepresentationBaseType, _altova_mil_altova_CRepresentationBaseType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("RepresentationType"), _altova_ti_altova_CRepresentationBaseType, _altova_mif_altova_CRepresentationType, _altova_mil_altova_CRepresentationType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SAPType"), _altova_ti_xs_altova_CunsignedInt, _altova_mif_altova_CSAPType, _altova_mil_altova_CSAPType,  98 , altova::Whitespace_Unknown, &altova::IntegerFormatter },
	{ &binder, _altova_ni, _T("SegmentBaseType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CSegmentBaseType, _altova_mil_altova_CSegmentBaseType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SegmentListType"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_mif_altova_CSegmentListType, _altova_mil_altova_CSegmentListType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SegmentTemplateType"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_mif_altova_CSegmentTemplateType, _altova_mil_altova_CSegmentTemplateType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SegmentTimelineType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CSegmentTimelineType, _altova_mil_altova_CSegmentTimelineType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SegmentURLType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CSegmentURLType, _altova_mil_altova_CSegmentURLType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("StringVectorType"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_altova_CStringVectorType, _altova_mil_altova_CStringVectorType,  101 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T("SubRepresentationType"), _altova_ti_altova_CRepresentationBaseType, _altova_mif_altova_CSubRepresentationType, _altova_mil_altova_CSubRepresentationType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("SubsetType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CSubsetType, _altova_mil_altova_CSubsetType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("UIntVectorType"), _altova_ti_xs_altova_CanySimpleType, _altova_mif_altova_CUIntVectorType, _altova_mil_altova_CUIntVectorType,  103 , altova::Whitespace_Collapse, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T("URLType"), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CURLType, _altova_mil_altova_CURLType,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T("VideoScanType"), _altova_ti_xs_altova_Cstring, _altova_mif_altova_CVideoScanType, _altova_mil_altova_CVideoScanType,  106 , altova::Whitespace_Unknown, &altova::AnySimpleTypeFormatter },
	{ &binder, _altova_ni, _T("MPDSchema"), ~0, _altova_mif_altova_CMPDSchema, _altova_mil_altova_CMPDSchema,  ~0 , altova::Whitespace_Unknown },
	{ &binder, _altova_ni, _T(""), _altova_ti_xs_altova_CanyType, _altova_mif_altova_CSType, _altova_mil_altova_CSType,  ~0 , altova::Whitespace_Unknown },

{ 0 },
};

const altova::MemberInfo members[] = 
{
	{ &binder, _T(""), _T(""), _altova_ti_xs_altova_CanyType, _altova_ti_xs_altova_CanySimpleType, MemberFlags_IsAttribute, 0, -1 },

	{ &binder, _T(""), _T(""), _altova_ti_xs_altova_CanyURIType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 1, 1 },

	{ &binder, _T(""), _T(""), _altova_ti_xs_altova_CstringType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },

	{ &binder, _T(""), _T("profiles"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("width"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("height"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("sar"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("frameRate"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("audioSamplingRate"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("mimeType"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("segmentProfiles"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codecs"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maximumSAPPeriod"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("startWithSAP"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CSAPType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxPlayoutRate"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codingDependency"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("scanType"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CVideoScanType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("id"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("group"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("lang"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Clanguage, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("contentType"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("par"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("minBandwidth"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxBandwidth"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("minWidth"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxWidth"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("minHeight"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxHeight"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("minFrameRate"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxFrameRate"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("segmentAlignment"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CConditionalUintType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("subsegmentAlignment"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CConditionalUintType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("subsegmentStartsWithSAP"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CSAPType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("bitstreamSwitching"), _altova_ti_altova_CAdaptationSetType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("FramePacking"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("AudioChannelConfiguration"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("ContentProtection"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CContentProtectionType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Accessibility"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Role"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Rating"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Viewpoint"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("ContentComponent"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CContentComponentType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("BaseURL"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CBaseURLType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentBase"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CSegmentBaseType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentList"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CSegmentListType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentTemplate"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CSegmentTemplateType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Representation"), _altova_ti_altova_CAdaptationSetType, _altova_ti_altova_CRepresentationType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T(""), _altova_ti_altova_CBaseURLType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("serviceLocation"), _altova_ti_altova_CBaseURLType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("byteRange"), _altova_ti_altova_CBaseURLType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T(""), _T("id"), _altova_ti_altova_CContentComponentType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("lang"), _altova_ti_altova_CContentComponentType, _altova_ti_xs_altova_Clanguage, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("contentType"), _altova_ti_altova_CContentComponentType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("par"), _altova_ti_altova_CContentComponentType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Accessibility"), _altova_ti_altova_CContentComponentType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Role"), _altova_ti_altova_CContentComponentType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Rating"), _altova_ti_altova_CContentComponentType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Viewpoint"), _altova_ti_altova_CContentComponentType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("schemeIdUri"), _altova_ti_altova_CContentProtectionType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("value"), _altova_ti_altova_CContentProtectionType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("FormatVersion"), _altova_ti_altova_CContentProtectionType, _altova_ti_altova_CFormatVersionType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("MarlinContentIds"), _altova_ti_altova_CContentProtectionType, _altova_ti_altova_CMarlinContentIdsType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("MarlinBroadband"), _altova_ti_altova_CContentProtectionType, _altova_ti_altova_CMarlinBroadbandType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("MS3"), _altova_ti_altova_CContentProtectionType, _altova_ti_altova_CMS3Type, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("schemeIdUri"), _altova_ti_altova_CDescriptorType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("value"), _altova_ti_altova_CDescriptorType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T(""), _T("major"), _altova_ti_altova_CFormatVersionType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("minor"), _altova_ti_altova_CFormatVersionType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },

	{ &binder, _T(""), _T("id"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("profiles"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("type"), _altova_ti_altova_CMPDtype, _altova_ti_altova_CPresentationType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("availabilityStartTime"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_CdateTime, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("availabilityEndTime"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_CdateTime, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("mediaPresentationDuration"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("minimumUpdatePeriod"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("minBufferTime"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("timeShiftBufferDepth"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("suggestedPresentationDelay"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxSegmentDuration"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxSubsegmentDuration"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("ProgramInformation"), _altova_ti_altova_CMPDtype, _altova_ti_altova_CProgramInformationType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("BaseURL"), _altova_ti_altova_CMPDtype, _altova_ti_altova_CBaseURLType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Location"), _altova_ti_altova_CMPDtype, _altova_ti_xs_altova_CanyURIType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Period"), _altova_ti_altova_CMPDtype, _altova_ti_altova_CPeriodType, MemberFlags_None, 1, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Metrics"), _altova_ti_altova_CMPDtype, _altova_ti_altova_CMetricsType, MemberFlags_None, 0, -1 },

	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("URIsAreTemplated"), _altova_ti_altova_CMS3Type, _altova_ti_xs_altova_CanyURIType, MemberFlags_None, 0, 1 },

	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SilentRightsUrl"), _altova_ti_altova_CMarlinBroadbandType, _altova_ti_xs_altova_CanyURIType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("PreviewRightsUrl"), _altova_ti_altova_CMarlinBroadbandType, _altova_ti_xs_altova_CanyURIType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("RightsIssuerUrl"), _altova_ti_altova_CMarlinBroadbandType, _altova_ti_xs_altova_CanyURIType, MemberFlags_None, 0, 1 },

	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("MarlinContentId"), _altova_ti_altova_CMarlinContentIdsType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 1, -1 },

	{ &binder, _T(""), _T("metrics"), _altova_ti_altova_CMetricsType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Reporting"), _altova_ti_altova_CMetricsType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 1, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Range"), _altova_ti_altova_CMetricsType, _altova_ti_altova_CRangeType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("timescale"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("presentationTimeOffset"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRange"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRangeExact"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("duration"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("startNumber"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialisation"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialization"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("RepresentationIndex"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentTimeline"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_altova_CSegmentTimelineType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("BitstreamSwitching"), _altova_ti_altova_CMultipleSegmentBaseType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("id"), _altova_ti_altova_CPeriodType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("start"), _altova_ti_altova_CPeriodType, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("duration"), _altova_ti_altova_CPeriodType, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("bitstreamSwitching"), _altova_ti_altova_CPeriodType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("BaseURL"), _altova_ti_altova_CPeriodType, _altova_ti_altova_CBaseURLType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentBase"), _altova_ti_altova_CPeriodType, _altova_ti_altova_CSegmentBaseType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentList"), _altova_ti_altova_CPeriodType, _altova_ti_altova_CSegmentListType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentTemplate"), _altova_ti_altova_CPeriodType, _altova_ti_altova_CSegmentTemplateType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("AdaptationSet"), _altova_ti_altova_CPeriodType, _altova_ti_altova_CAdaptationSetType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Subset"), _altova_ti_altova_CPeriodType, _altova_ti_altova_CSubsetType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("lang"), _altova_ti_altova_CProgramInformationType, _altova_ti_xs_altova_Clanguage, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("moreInformationURL"), _altova_ti_altova_CProgramInformationType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Title"), _altova_ti_altova_CProgramInformationType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Source"), _altova_ti_altova_CProgramInformationType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Copyright"), _altova_ti_altova_CProgramInformationType, _altova_ti_xs_altova_CstringType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("starttime"), _altova_ti_altova_CRangeType, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("duration"), _altova_ti_altova_CRangeType, _altova_ti_xs_altova_Cduration, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T(""), _T("profiles"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("width"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("height"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("sar"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("frameRate"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("audioSamplingRate"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("mimeType"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("segmentProfiles"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codecs"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maximumSAPPeriod"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("startWithSAP"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_altova_CSAPType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxPlayoutRate"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codingDependency"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("scanType"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_altova_CVideoScanType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("FramePacking"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("AudioChannelConfiguration"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("ContentProtection"), _altova_ti_altova_CRepresentationBaseType, _altova_ti_altova_CContentProtectionType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("profiles"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("width"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("height"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("sar"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("frameRate"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("audioSamplingRate"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("mimeType"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("segmentProfiles"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codecs"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maximumSAPPeriod"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("startWithSAP"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CSAPType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxPlayoutRate"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codingDependency"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("scanType"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CVideoScanType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("id"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("bandwidth"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("qualityRanking"), _altova_ti_altova_CRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("dependencyId"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CStringVectorType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("mediaStreamStructureId"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CStringVectorType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("FramePacking"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("AudioChannelConfiguration"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("ContentProtection"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CContentProtectionType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("BaseURL"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CBaseURLType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SubRepresentation"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CSubRepresentationType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentBase"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CSegmentBaseType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentList"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CSegmentListType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentTemplate"), _altova_ti_altova_CRepresentationType, _altova_ti_altova_CSegmentTemplateType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("timescale"), _altova_ti_altova_CSegmentBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("presentationTimeOffset"), _altova_ti_altova_CSegmentBaseType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRange"), _altova_ti_altova_CSegmentBaseType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRangeExact"), _altova_ti_altova_CSegmentBaseType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialisation"), _altova_ti_altova_CSegmentBaseType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialization"), _altova_ti_altova_CSegmentBaseType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("RepresentationIndex"), _altova_ti_altova_CSegmentBaseType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("timescale"), _altova_ti_altova_CSegmentListType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("presentationTimeOffset"), _altova_ti_altova_CSegmentListType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRange"), _altova_ti_altova_CSegmentListType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRangeExact"), _altova_ti_altova_CSegmentListType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("duration"), _altova_ti_altova_CSegmentListType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("startNumber"), _altova_ti_altova_CSegmentListType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialisation"), _altova_ti_altova_CSegmentListType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialization"), _altova_ti_altova_CSegmentListType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("RepresentationIndex"), _altova_ti_altova_CSegmentListType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentTimeline"), _altova_ti_altova_CSegmentListType, _altova_ti_altova_CSegmentTimelineType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("BitstreamSwitching"), _altova_ti_altova_CSegmentListType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentURL"), _altova_ti_altova_CSegmentListType, _altova_ti_altova_CSegmentURLType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("timescale"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("presentationTimeOffset"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRange"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRangeExact"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("duration"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("startNumber"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("media"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("index"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("initialisation"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("initialization"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("bitstreamSwitching"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialisation"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("Initialization"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("RepresentationIndex"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("SegmentTimeline"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_altova_CSegmentTimelineType, MemberFlags_None, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("BitstreamSwitching"), _altova_ti_altova_CSegmentTemplateType, _altova_ti_altova_CURLType, MemberFlags_None, 0, 1 },

	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("S"), _altova_ti_altova_CSegmentTimelineType, _altova_ti_altova_CSType, MemberFlags_None, 1, -1 },

	{ &binder, _T(""), _T("media"), _altova_ti_altova_CSegmentURLType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("mediaRange"), _altova_ti_altova_CSegmentURLType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("index"), _altova_ti_altova_CSegmentURLType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("indexRange"), _altova_ti_altova_CSegmentURLType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T(""), _T("profiles"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("width"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("height"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("sar"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("frameRate"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("audioSamplingRate"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("mimeType"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("segmentProfiles"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codecs"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maximumSAPPeriod"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("startWithSAP"), _altova_ti_altova_CSubRepresentationType, _altova_ti_altova_CSAPType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("maxPlayoutRate"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cdouble, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("codingDependency"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_Cboolean, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("scanType"), _altova_ti_altova_CSubRepresentationType, _altova_ti_altova_CVideoScanType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("level"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("dependencyLevel"), _altova_ti_altova_CSubRepresentationType, _altova_ti_altova_CUIntVectorType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("bandwidth"), _altova_ti_altova_CSubRepresentationType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("contentComponent"), _altova_ti_altova_CSubRepresentationType, _altova_ti_altova_CStringVectorType, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("FramePacking"), _altova_ti_altova_CSubRepresentationType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("AudioChannelConfiguration"), _altova_ti_altova_CSubRepresentationType, _altova_ti_altova_CDescriptorType, MemberFlags_None, 0, -1 },
	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("ContentProtection"), _altova_ti_altova_CSubRepresentationType, _altova_ti_altova_CContentProtectionType, MemberFlags_None, 0, -1 },

	{ &binder, _T(""), _T("contains"), _altova_ti_altova_CSubsetType, _altova_ti_altova_CUIntVectorType, MemberFlags_IsAttribute, 1, 1 },

	{ &binder, _T(""), _T("sourceURL"), _altova_ti_altova_CURLType, _altova_ti_xs_altova_CanyURI, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("range"), _altova_ti_altova_CURLType, _altova_ti_xs_altova_Cstring, MemberFlags_IsAttribute, 0, 1 },

	{ &binder, _T("urn:mpeg:dash:schema:mpd:2011"), _T("MPD"), _altova_ti_altova_CMPDSchema, _altova_ti_altova_CMPDtype, MemberFlags_None, 0, 1 },

	{ &binder, _T(""), _T("t"), _altova_ti_altova_CSType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },
	{ &binder, _T(""), _T("d"), _altova_ti_altova_CSType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 1, 1 },
	{ &binder, _T(""), _T("r"), _altova_ti_altova_CSType, _altova_ti_xs_altova_CunsignedInt, MemberFlags_IsAttribute, 0, 1 },

{ 0 },
};

const altova::FacetInfo facets[] = 
{
	// ENTITIES
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, _T("minLength"), _T("1"), 1 }, 
	{ 0, 0, 0, 0 },
	// IDREFS
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, _T("minLength"), _T("1"), 1 }, 
	{ 0, 0, 0, 0 },
	// NCName
	{ 0, _T("pattern"), _T("[\\i-[:]][\\c-[:]]*"), 0 }, 
	{ 0, 0, 0, 0 },
	// NMTOKEN
	{ 0, _T("pattern"), _T("\\c+"), 0 }, 
	{ 0, 0, 0, 0 },
	// NMTOKENS
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, _T("minLength"), _T("1"), 1 }, 
	{ 0, _T("pattern"), _T("\\c+"), 0 }, 
	{ 0, _T("pattern"), _T("\\c+"), 0 }, 
	{ 0, 0, 0, 0 },
	// NOTATION
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// Name
	{ 0, _T("pattern"), _T("\\i\\c*"), 0 }, 
	{ 0, 0, 0, 0 },
	// QName
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// anyURI
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// base64Binary
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// boolean
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// byte
	{ 0, _T("minInclusive"), _T("-128"), 0 }, 
	{ 0, _T("maxInclusive"), _T("127"), 0 }, 
	{ 0, 0, 0, 0 },
	// date
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// dateTime
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// decimal
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// double
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// duration
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// float
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gDay
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gMonth
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gMonthDay
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gYear
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// gYearMonth
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// hexBinary
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// int
	{ 0, _T("minInclusive"), _T("-2147483648"), 0 }, 
	{ 0, _T("maxInclusive"), _T("2147483647"), 0 }, 
	{ 0, 0, 0, 0 },
	// integer
	{ 0, _T("fractionDigits"), _T("0"), 0 }, 
	{ 0, _T("pattern"), _T("[\\-+]?[0-9]+"), 0 }, 
	{ 0, 0, 0, 0 },
	// language
	{ 0, _T("pattern"), _T("[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"), 0 }, 
	{ 0, 0, 0, 0 },
	// long
	{ 0, _T("minInclusive"), _T("-9223372036854775808"), 0 }, 
	{ 0, _T("maxInclusive"), _T("9223372036854775807"), 0 }, 
	{ 0, 0, 0, 0 },
	// negativeInteger
	{ 0, _T("maxInclusive"), _T("-1"), 0 }, 
	{ 0, 0, 0, 0 },
	// nonNegativeInteger
	{ 0, _T("minInclusive"), _T("0"), 0 }, 
	{ 0, 0, 0, 0 },
	// nonPositiveInteger
	{ 0, _T("maxInclusive"), _T("0"), 0 }, 
	{ 0, 0, 0, 0 },
	// normalizedString
	{ 0, _T("whitespace"), _T("replace"), 0 },
	{ 0, 0, 0, 0 },
	// positiveInteger
	{ 0, _T("minInclusive"), _T("1"), 0 }, 
	{ 0, 0, 0, 0 },
	// short
	{ 0, _T("minInclusive"), _T("-32768"), 0 }, 
	{ 0, _T("maxInclusive"), _T("32767"), 0 }, 
	{ 0, 0, 0, 0 },
	// string
	{ 0, _T("whitespace"), _T("preserve"), 0 },
	{ 0, 0, 0, 0 },
	// time
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// token
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// unsignedByte
	{ 0, _T("maxInclusive"), _T("255"), 0 }, 
	{ 0, 0, 0, 0 },
	// unsignedInt
	{ 0, _T("maxInclusive"), _T("4294967295"), 0 }, 
	{ 0, 0, 0, 0 },
	// unsignedLong
	{ 0, _T("maxInclusive"), _T("18446744073709551615"), 0 }, 
	{ 0, 0, 0, 0 },
	// unsignedShort
	{ 0, _T("maxInclusive"), _T("65535"), 0 }, 
	{ 0, 0, 0, 0 },
	// ConditionalUintType
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, _T("maxInclusive"), _T("4294967295"), 0 }, 
	{ 0, 0, 0, 0 },
	// PresentationType
	{ 0, _T("enumeration"), _T("static"), 0 }, 
	{ 0, _T("enumeration"), _T("dynamic"), 0 }, 
	{ 0, 0, 0, 0 },
	// SAPType
	{ 0, _T("minInclusive"), _T("0"), 0 }, 
	{ 0, _T("maxInclusive"), _T("6"), 0 }, 
	{ 0, 0, 0, 0 },
	// StringVectorType
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, 0, 0, 0 },
	// UIntVectorType
	{ 0, _T("whitespace"), _T("collapse"), 0 },
	{ 0, _T("maxInclusive"), _T("4294967295"), 0 }, 
	{ 0, 0, 0, 0 },
	// VideoScanType
	{ 0, _T("enumeration"), _T("progressive"), 0 }, 
	{ 0, _T("enumeration"), _T("interlaced"), 0 }, 
	{ 0, _T("enumeration"), _T("unknown"), 0 }, 
	{ 0, 0, 0, 0 },
{ 0 },
};

}  // namespace MPDSchema
