////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2012r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#ifndef MPDSchema_PREFIX_H_INCLUDED
#define MPDSchema_PREFIX_H_INCLUDED




#include "MPDSchema_debug.h"
#include "MPDSchema_enum.h"


#include <xercesc/dom/DOM.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>



#include "Altova.h"
#include "SchemaTypes.h"
#include "AltovaException.h"

#include "XmlException.h"
#include "Node.h"
using namespace altova;


//{{AFX_INSERT_LOCATION}}

#endif // MPDSchema_STDAFX_H_INCLUDED
