////////////////////////////////////////////////////////////////////////
//
// XmlException.cpp
//
// This file was generated by XMLSpy 2012r2sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#include "altova_xml_prefix.h"
#include "Altova.h"
#include "SchemaTypes.h"
#include "XmlException.h"

namespace altova {


CXmlException::CXmlException(int nCode, const tstring& sMessage)
	: CAltovaException(nCode, sMessage)
{
}


} // namespace altova
